[2021-10-28 12:28:24,558] {scheduler_job.py:182} INFO - Started process (PID=458) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:28:24,584] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:28:24,615] {logging_mixin.py:104} INFO - [2021-10-28 12:28:24,613] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:28:38,858] {logging_mixin.py:104} INFO - [2021-10-28 12:28:38,741] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:28:38,893] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:28:39,003] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 14.538 seconds
[2021-10-28 12:29:57,566] {scheduler_job.py:182} INFO - Started process (PID=577) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:29:57,579] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:29:57,603] {logging_mixin.py:104} INFO - [2021-10-28 12:29:57,597] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:30:32,111] {logging_mixin.py:104} INFO - [2021-10-28 12:30:31,950] {timeout.py:36} ERROR - Process timed out, PID: 577
[2021-10-28 12:30:32,430] {logging_mixin.py:104} WARNING - Exception ignored in: <function _collection_gced at 0x40038117b8>
[2021-10-28 12:30:32,485] {logging_mixin.py:104} WARNING - Traceback (most recent call last):
[2021-10-28 12:30:32,526] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/event/registry.py", line 53, in _collection_gced
[2021-10-28 12:30:32,794] {logging_mixin.py:104} WARNING -     def _collection_gced(ref):
[2021-10-28 12:30:32,802] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
[2021-10-28 12:30:32,815] {logging_mixin.py:104} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2021-10-28 12:30:32,840] {logging_mixin.py:104} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/ricochet_stream_closure.py after 30.0s, PID: 577
[2021-10-28 12:30:45,137] {logging_mixin.py:104} INFO - [2021-10-28 12:30:44,676] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:30:45,257] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:30:45,479] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 47.961 seconds
[2021-10-28 12:31:41,519] {scheduler_job.py:182} INFO - Started process (PID=695) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:31:41,540] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:31:41,580] {logging_mixin.py:104} INFO - [2021-10-28 12:31:41,567] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:32:00,858] {logging_mixin.py:104} INFO - [2021-10-28 12:31:59,136] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:32:00,955] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:32:01,128] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 19.653 seconds
[2021-10-28 12:32:32,368] {scheduler_job.py:182} INFO - Started process (PID=751) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:32:32,376] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:32:32,384] {logging_mixin.py:104} INFO - [2021-10-28 12:32:32,383] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:32:37,654] {logging_mixin.py:104} INFO - [2021-10-28 12:32:37,604] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:32:37,660] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:32:37,694] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 5.346 seconds
[2021-10-28 12:33:07,830] {scheduler_job.py:182} INFO - Started process (PID=804) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:33:07,837] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:33:07,841] {logging_mixin.py:104} INFO - [2021-10-28 12:33:07,840] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:33:10,760] {logging_mixin.py:104} INFO - [2021-10-28 12:33:10,730] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:33:10,767] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:33:10,790] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.967 seconds
[2021-10-28 12:33:40,962] {scheduler_job.py:182} INFO - Started process (PID=857) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:33:40,968] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:33:40,972] {logging_mixin.py:104} INFO - [2021-10-28 12:33:40,971] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:33:44,992] {logging_mixin.py:104} INFO - [2021-10-28 12:33:44,950] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:33:45,005] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:33:45,024] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 4.080 seconds
[2021-10-28 12:34:15,624] {scheduler_job.py:182} INFO - Started process (PID=913) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:34:15,633] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:34:15,636] {logging_mixin.py:104} INFO - [2021-10-28 12:34:15,636] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:34:18,843] {logging_mixin.py:104} INFO - [2021-10-28 12:34:18,818] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:34:18,852] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:34:18,878] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 3.278 seconds
[2021-10-28 12:34:49,077] {scheduler_job.py:182} INFO - Started process (PID=968) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:34:49,081] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:34:49,084] {logging_mixin.py:104} INFO - [2021-10-28 12:34:49,084] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:34:51,462] {logging_mixin.py:104} INFO - [2021-10-28 12:34:51,438] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:34:51,466] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:34:51,481] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.411 seconds
[2021-10-28 12:35:21,714] {scheduler_job.py:182} INFO - Started process (PID=1023) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:35:21,719] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:35:21,721] {logging_mixin.py:104} INFO - [2021-10-28 12:35:21,720] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:35:25,588] {logging_mixin.py:104} INFO - [2021-10-28 12:35:25,565] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:35:25,594] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:35:25,609] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 3.900 seconds
[2021-10-28 12:35:55,708] {scheduler_job.py:182} INFO - Started process (PID=1077) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:35:55,714] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:35:55,719] {logging_mixin.py:104} INFO - [2021-10-28 12:35:55,718] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:35:58,474] {logging_mixin.py:104} INFO - [2021-10-28 12:35:58,453] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:35:58,479] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:35:58,490] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.789 seconds
[2021-10-28 12:36:29,056] {scheduler_job.py:182} INFO - Started process (PID=1134) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:36:29,060] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:36:29,063] {logging_mixin.py:104} INFO - [2021-10-28 12:36:29,063] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:36:31,512] {logging_mixin.py:104} INFO - [2021-10-28 12:36:31,492] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:36:31,516] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:36:31,527] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.478 seconds
[2021-10-28 12:37:02,103] {scheduler_job.py:182} INFO - Started process (PID=1190) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:37:02,110] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:37:02,114] {logging_mixin.py:104} INFO - [2021-10-28 12:37:02,114] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:37:04,421] {logging_mixin.py:104} INFO - [2021-10-28 12:37:04,400] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:37:04,425] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:37:04,437] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.344 seconds
[2021-10-28 12:37:35,096] {scheduler_job.py:182} INFO - Started process (PID=1248) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:37:35,102] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:37:35,106] {logging_mixin.py:104} INFO - [2021-10-28 12:37:35,106] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:37:37,483] {logging_mixin.py:104} INFO - [2021-10-28 12:37:37,448] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:37:37,488] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:37:37,499] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.416 seconds
[2021-10-28 12:38:07,980] {scheduler_job.py:182} INFO - Started process (PID=1303) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:38:07,985] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:38:07,990] {logging_mixin.py:104} INFO - [2021-10-28 12:38:07,989] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:38:10,346] {logging_mixin.py:104} INFO - [2021-10-28 12:38:10,327] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:38:10,351] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:38:10,364] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.391 seconds
[2021-10-28 12:38:40,534] {scheduler_job.py:182} INFO - Started process (PID=1356) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:38:40,538] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:38:40,541] {logging_mixin.py:104} INFO - [2021-10-28 12:38:40,541] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:38:43,054] {logging_mixin.py:104} INFO - [2021-10-28 12:38:43,032] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:38:43,059] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:38:43,072] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.544 seconds
[2021-10-28 12:39:13,207] {scheduler_job.py:182} INFO - Started process (PID=1410) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:39:13,213] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:39:13,216] {logging_mixin.py:104} INFO - [2021-10-28 12:39:13,215] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:39:15,662] {logging_mixin.py:104} INFO - [2021-10-28 12:39:15,639] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:39:15,666] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:39:15,678] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.483 seconds
[2021-10-28 12:39:46,061] {scheduler_job.py:182} INFO - Started process (PID=1465) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:39:46,068] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:39:46,071] {logging_mixin.py:104} INFO - [2021-10-28 12:39:46,071] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:39:48,526] {logging_mixin.py:104} INFO - [2021-10-28 12:39:48,498] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:39:48,532] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:39:48,546] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.497 seconds
[2021-10-28 12:40:18,869] {scheduler_job.py:182} INFO - Started process (PID=1521) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:40:18,875] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:40:18,878] {logging_mixin.py:104} INFO - [2021-10-28 12:40:18,878] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:40:21,043] {logging_mixin.py:104} INFO - [2021-10-28 12:40:21,025] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:40:21,046] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:40:21,056] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.199 seconds
[2021-10-28 12:40:51,184] {scheduler_job.py:182} INFO - Started process (PID=1575) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:40:51,187] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:40:51,190] {logging_mixin.py:104} INFO - [2021-10-28 12:40:51,189] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:40:53,401] {logging_mixin.py:104} INFO - [2021-10-28 12:40:53,380] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:40:53,406] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:40:53,418] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.240 seconds
[2021-10-28 12:41:23,873] {scheduler_job.py:182} INFO - Started process (PID=1630) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:41:23,877] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:41:23,880] {logging_mixin.py:104} INFO - [2021-10-28 12:41:23,879] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:41:26,100] {logging_mixin.py:104} INFO - [2021-10-28 12:41:26,078] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:41:26,103] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:41:26,115] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.250 seconds
[2021-10-28 12:41:56,277] {scheduler_job.py:182} INFO - Started process (PID=1685) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:41:56,280] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:41:56,282] {logging_mixin.py:104} INFO - [2021-10-28 12:41:56,282] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:42:00,099] {logging_mixin.py:104} INFO - [2021-10-28 12:42:00,078] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:42:00,103] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:42:00,115] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 3.845 seconds
[2021-10-28 12:42:30,421] {scheduler_job.py:182} INFO - Started process (PID=1750) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:42:30,424] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:42:30,427] {logging_mixin.py:104} INFO - [2021-10-28 12:42:30,427] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:42:32,826] {logging_mixin.py:104} INFO - [2021-10-28 12:42:32,807] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:42:32,832] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:42:32,841] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.428 seconds
[2021-10-28 12:43:02,987] {scheduler_job.py:182} INFO - Started process (PID=1813) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:43:02,995] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:43:02,998] {logging_mixin.py:104} INFO - [2021-10-28 12:43:02,998] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:43:05,541] {logging_mixin.py:104} INFO - [2021-10-28 12:43:05,521] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:43:05,544] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:43:05,557] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.576 seconds
[2021-10-28 12:43:35,799] {scheduler_job.py:182} INFO - Started process (PID=1867) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:43:35,804] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:43:35,807] {logging_mixin.py:104} INFO - [2021-10-28 12:43:35,807] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:43:38,496] {logging_mixin.py:104} INFO - [2021-10-28 12:43:38,471] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:43:38,504] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:43:38,519] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.727 seconds
[2021-10-28 12:44:08,650] {scheduler_job.py:182} INFO - Started process (PID=1918) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:44:08,654] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:44:08,656] {logging_mixin.py:104} INFO - [2021-10-28 12:44:08,655] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:44:10,803] {logging_mixin.py:104} INFO - [2021-10-28 12:44:10,785] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:44:10,807] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:44:10,817] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.173 seconds
[2021-10-28 12:44:41,089] {scheduler_job.py:182} INFO - Started process (PID=1973) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:44:41,093] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:44:41,095] {logging_mixin.py:104} INFO - [2021-10-28 12:44:41,094] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:44:43,162] {logging_mixin.py:104} INFO - [2021-10-28 12:44:43,144] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:44:43,167] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:44:43,177] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.093 seconds
[2021-10-28 12:45:13,912] {scheduler_job.py:182} INFO - Started process (PID=2032) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:45:13,916] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:45:13,919] {logging_mixin.py:104} INFO - [2021-10-28 12:45:13,919] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:45:16,254] {logging_mixin.py:104} INFO - [2021-10-28 12:45:16,234] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:45:16,257] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:45:16,267] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.362 seconds
[2021-10-28 12:45:46,429] {scheduler_job.py:182} INFO - Started process (PID=2089) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:45:46,433] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:45:46,435] {logging_mixin.py:104} INFO - [2021-10-28 12:45:46,435] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:45:48,753] {logging_mixin.py:104} INFO - [2021-10-28 12:45:48,734] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:45:48,757] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:45:48,768] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.345 seconds
[2021-10-28 12:46:18,883] {scheduler_job.py:182} INFO - Started process (PID=2140) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:46:18,889] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:46:18,892] {logging_mixin.py:104} INFO - [2021-10-28 12:46:18,891] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:46:21,206] {logging_mixin.py:104} INFO - [2021-10-28 12:46:21,185] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:46:21,211] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:46:21,222] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.348 seconds
[2021-10-28 12:46:51,307] {scheduler_job.py:182} INFO - Started process (PID=2194) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:46:51,311] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:46:51,314] {logging_mixin.py:104} INFO - [2021-10-28 12:46:51,314] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:46:53,340] {logging_mixin.py:104} INFO - [2021-10-28 12:46:53,321] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:46:53,344] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:46:53,354] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.056 seconds
[2021-10-28 12:47:23,985] {scheduler_job.py:182} INFO - Started process (PID=2248) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:47:23,990] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:47:23,994] {logging_mixin.py:104} INFO - [2021-10-28 12:47:23,994] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:47:26,102] {logging_mixin.py:104} INFO - [2021-10-28 12:47:26,083] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:47:26,106] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:47:26,117] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.142 seconds
[2021-10-28 12:47:56,274] {scheduler_job.py:182} INFO - Started process (PID=2313) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:47:56,278] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:47:56,281] {logging_mixin.py:104} INFO - [2021-10-28 12:47:56,280] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:47:58,706] {logging_mixin.py:104} INFO - [2021-10-28 12:47:58,685] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:47:58,711] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:47:58,722] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.454 seconds
[2021-10-28 12:48:29,655] {scheduler_job.py:182} INFO - Started process (PID=2376) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:48:29,660] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:48:29,663] {logging_mixin.py:104} INFO - [2021-10-28 12:48:29,662] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:48:32,220] {logging_mixin.py:104} INFO - [2021-10-28 12:48:32,198] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:48:32,224] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:48:32,238] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.590 seconds
[2021-10-28 12:49:02,665] {scheduler_job.py:182} INFO - Started process (PID=2433) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:49:02,669] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:49:02,671] {logging_mixin.py:104} INFO - [2021-10-28 12:49:02,671] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:49:05,263] {logging_mixin.py:104} INFO - [2021-10-28 12:49:05,243] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:49:05,267] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:49:05,278] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.620 seconds
[2021-10-28 12:49:35,555] {scheduler_job.py:182} INFO - Started process (PID=2488) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:49:35,562] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:49:35,565] {logging_mixin.py:104} INFO - [2021-10-28 12:49:35,564] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:49:37,567] {logging_mixin.py:104} INFO - [2021-10-28 12:49:37,549] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:49:37,569] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:49:37,579] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.033 seconds
[2021-10-28 12:50:07,970] {scheduler_job.py:182} INFO - Started process (PID=2541) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:50:07,975] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:50:07,979] {logging_mixin.py:104} INFO - [2021-10-28 12:50:07,979] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:50:10,097] {logging_mixin.py:104} INFO - [2021-10-28 12:50:10,078] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:50:10,102] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:50:10,112] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.152 seconds
[2021-10-28 12:50:40,585] {scheduler_job.py:182} INFO - Started process (PID=2595) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:50:40,589] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:50:40,592] {logging_mixin.py:104} INFO - [2021-10-28 12:50:40,592] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:50:42,635] {logging_mixin.py:104} INFO - [2021-10-28 12:50:42,615] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:50:42,642] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:50:42,653] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.074 seconds
[2021-10-28 12:51:13,446] {scheduler_job.py:182} INFO - Started process (PID=2650) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:51:13,450] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:51:13,452] {logging_mixin.py:104} INFO - [2021-10-28 12:51:13,452] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:51:15,747] {logging_mixin.py:104} INFO - [2021-10-28 12:51:15,728] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:51:15,750] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:51:15,761] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.320 seconds
[2021-10-28 12:51:46,260] {scheduler_job.py:182} INFO - Started process (PID=2703) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:51:46,265] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:51:46,268] {logging_mixin.py:104} INFO - [2021-10-28 12:51:46,268] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:51:49,300] {logging_mixin.py:104} INFO - [2021-10-28 12:51:49,276] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:51:49,305] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:51:49,321] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 3.077 seconds
[2021-10-28 12:52:19,819] {scheduler_job.py:182} INFO - Started process (PID=2755) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:52:19,825] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:52:19,827] {logging_mixin.py:104} INFO - [2021-10-28 12:52:19,827] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:52:22,222] {logging_mixin.py:104} INFO - [2021-10-28 12:52:22,201] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:52:22,226] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:52:22,237] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.426 seconds
[2021-10-28 12:52:53,178] {scheduler_job.py:182} INFO - Started process (PID=2820) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:52:53,186] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 12:52:53,189] {logging_mixin.py:104} INFO - [2021-10-28 12:52:53,189] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:52:55,487] {logging_mixin.py:104} INFO - [2021-10-28 12:52:55,467] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 12:52:55,492] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 12:52:55,505] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.339 seconds
[2021-10-28 13:02:10,652] {scheduler_job.py:182} INFO - Started process (PID=446) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:02:10,670] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:02:10,684] {logging_mixin.py:104} INFO - [2021-10-28 13:02:10,682] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:02:19,098] {logging_mixin.py:104} INFO - [2021-10-28 13:02:19,034] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 13:02:19,110] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:02:19,167] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 8.534 seconds
[2021-10-28 13:02:49,374] {scheduler_job.py:182} INFO - Started process (PID=500) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:02:49,382] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:02:49,390] {logging_mixin.py:104} INFO - [2021-10-28 13:02:49,389] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:02:53,804] {logging_mixin.py:104} INFO - [2021-10-28 13:02:53,764] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 13:02:53,817] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:02:53,849] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 4.489 seconds
[2021-10-28 13:03:28,459] {scheduler_job.py:182} INFO - Started process (PID=553) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:03:28,467] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:03:28,471] {logging_mixin.py:104} INFO - [2021-10-28 13:03:28,471] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:03:31,775] {logging_mixin.py:104} INFO - [2021-10-28 13:03:31,742] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 13:03:31,782] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:03:31,801] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 3.359 seconds
[2021-10-28 13:04:02,680] {scheduler_job.py:182} INFO - Started process (PID=606) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:04:02,684] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:04:02,687] {logging_mixin.py:104} INFO - [2021-10-28 13:04:02,687] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:04:05,819] {logging_mixin.py:104} INFO - [2021-10-28 13:04:05,789] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 13:04:05,826] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:04:05,843] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 3.171 seconds
[2021-10-28 13:04:36,783] {scheduler_job.py:182} INFO - Started process (PID=659) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:04:36,787] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:04:36,789] {logging_mixin.py:104} INFO - [2021-10-28 13:04:36,789] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:04:40,333] {logging_mixin.py:104} INFO - [2021-10-28 13:04:40,293] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 13:04:40,342] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:04:40,365] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 3.587 seconds
[2021-10-28 13:05:10,433] {scheduler_job.py:182} INFO - Started process (PID=715) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:05:10,441] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:05:10,445] {logging_mixin.py:104} INFO - [2021-10-28 13:05:10,445] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:05:13,854] {logging_mixin.py:104} INFO - [2021-10-28 13:05:13,822] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 13:05:13,863] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:05:13,882] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 3.454 seconds
[2021-10-28 13:05:44,792] {scheduler_job.py:182} INFO - Started process (PID=787) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:05:44,796] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:05:44,801] {logging_mixin.py:104} INFO - [2021-10-28 13:05:44,800] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:05:47,910] {logging_mixin.py:104} INFO - [2021-10-28 13:05:47,868] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 13:05:47,937] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:05:47,966] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 3.180 seconds
[2021-10-28 13:06:18,561] {scheduler_job.py:182} INFO - Started process (PID=844) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:06:18,565] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:06:18,568] {logging_mixin.py:104} INFO - [2021-10-28 13:06:18,568] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:06:21,875] {logging_mixin.py:104} INFO - [2021-10-28 13:06:21,847] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 13:06:21,882] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:06:21,899] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 3.344 seconds
[2021-10-28 13:06:52,465] {scheduler_job.py:182} INFO - Started process (PID=900) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:06:52,470] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:06:52,485] {logging_mixin.py:104} INFO - [2021-10-28 13:06:52,485] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:06:55,900] {logging_mixin.py:104} INFO - [2021-10-28 13:06:55,870] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 13:06:55,908] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:06:55,925] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 3.467 seconds
[2021-10-28 13:14:37,137] {scheduler_job.py:182} INFO - Started process (PID=419) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:14:37,171] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:14:37,183] {logging_mixin.py:104} INFO - [2021-10-28 13:14:37,182] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:14:42,609] {logging_mixin.py:104} INFO - [2021-10-28 13:14:42,554] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 13:14:42,623] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:14:42,659] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 5.546 seconds
[2021-10-28 13:15:15,002] {scheduler_job.py:182} INFO - Started process (PID=475) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:15:15,016] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:15:15,022] {logging_mixin.py:104} INFO - [2021-10-28 13:15:15,022] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:15:19,779] {logging_mixin.py:104} INFO - [2021-10-28 13:15:19,712] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 13:15:19,804] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:15:19,850] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 4.865 seconds
[2021-10-28 13:15:54,023] {scheduler_job.py:182} INFO - Started process (PID=529) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:15:54,028] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:15:54,033] {logging_mixin.py:104} INFO - [2021-10-28 13:15:54,032] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:15:58,694] {logging_mixin.py:104} INFO - [2021-10-28 13:15:58,645] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 13:15:58,704] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:15:58,730] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 4.720 seconds
[2021-10-28 13:16:28,846] {scheduler_job.py:182} INFO - Started process (PID=581) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:16:28,850] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:16:28,853] {logging_mixin.py:104} INFO - [2021-10-28 13:16:28,853] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:16:31,956] {logging_mixin.py:104} INFO - [2021-10-28 13:16:31,922] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 13:16:31,963] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:16:31,980] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 3.142 seconds
[2021-10-28 13:17:03,489] {scheduler_job.py:182} INFO - Started process (PID=635) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:17:03,493] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:17:03,495] {logging_mixin.py:104} INFO - [2021-10-28 13:17:03,495] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:17:06,843] {logging_mixin.py:104} INFO - [2021-10-28 13:17:06,813] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 13:17:06,851] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:17:06,871] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 3.391 seconds
[2021-10-28 13:17:37,184] {scheduler_job.py:182} INFO - Started process (PID=693) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:17:37,188] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:17:37,190] {logging_mixin.py:104} INFO - [2021-10-28 13:17:37,189] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:17:40,752] {logging_mixin.py:104} INFO - [2021-10-28 13:17:40,708] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 13:17:40,762] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:17:40,785] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 3.608 seconds
[2021-10-28 13:18:10,953] {scheduler_job.py:182} INFO - Started process (PID=753) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:18:10,960] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:18:10,965] {logging_mixin.py:104} INFO - [2021-10-28 13:18:10,965] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:18:13,806] {logging_mixin.py:104} INFO - [2021-10-28 13:18:13,773] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 13:18:13,812] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:18:13,830] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 2.884 seconds
[2021-10-28 13:18:43,955] {scheduler_job.py:182} INFO - Started process (PID=806) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:18:43,998] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:18:44,001] {logging_mixin.py:104} INFO - [2021-10-28 13:18:44,001] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:18:47,943] {logging_mixin.py:104} INFO - [2021-10-28 13:18:47,912] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ricochet_stream_closure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ricochet_stream_closure.py", line 54, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 185, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/dags/blocksec_plugin/ricochet_streamer_close_operator.py", line 35, in __init__
    self.wallet = EthereumWalletHook(ethereum_wallet=ethereum_wallet)
  File "/opt/airflow/dags/blocksec_plugin/ethereum_wallet_hook.py", line 9, in __init__
    conn = self.get_connection(ethereum_wallet)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `0xe07c9696e00f23Fc7bAE76d037A115bfF33E28be` isn't defined
[2021-10-28 13:18:47,954] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:18:47,978] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ricochet_stream_closure.py took 4.039 seconds
[2021-10-28 13:19:19,372] {scheduler_job.py:182} INFO - Started process (PID=876) to work on /opt/airflow/dags/ricochet_stream_closure.py
[2021-10-28 13:19:19,392] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ricochet_stream_closure.py for tasks to queue
[2021-10-28 13:19:19,423] {logging_mixin.py:104} INFO - [2021-10-28 13:19:19,422] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ricochet_stream_closure.py
